kernelci/kernelci-jenkins

- config/jobs.groovy
Add missing kernel-build NODE_LABEL parameter and read the value of
the test-runner CALLBACK_ID parameter from the environment.
> config/jobs.groovy: fix job parameters

- plugins-base.txt
The copyartifact is used to copy artifacts between trigger and runner
jobs, so it is required.
> plugins-base.txt: add copyartifact

- docker-compose.yaml
Only use the .env file in docker-compose.yaml as the main one to
provide the values to use with the current deployment.  The other
files are there as examples and when included they override the values
from the .env file.
> docker-compose.yaml: only use .env file

- config/jobs.groovy
Include rootfs-build-trigger job which triggers rootfs image creation using
rootfs-builder job.
Signed-off-by: Lakshmipathi Ganapathi <lakshmipathi.ganapathi@collabora.com>
> Add rootfs image builder jenkins jobs

- jobs.groovy
Add a PIPELINE_VERSION parameter to the rootfs-builder job as this is
required in order to upload the rootfs images in a unique directory on
the storage server.
> T17420 jobs.groovy: add PIPELINE_VERSION to rootfs-builder

- restart-compose.sh
Add restart-compose.sh to stop any running Jenkins kernelci container
and recreate it.
> Add restart-compose.sh helper script

- .env-production
- jobs.groovy
Add KCI_MONITOR_CRON environment variable to define a cron trigger for
the kernel-tree-monitor job.  If not defined, no periodic trigger will
be set.
> jobs.groovy: use KCI_MONITOR_CRON environment variable

- jobs.groovy
Rename DOCKER_BASE and CONFIG_LIST to KCI_DOCKER_BASE and
KCI_CONFIG_LIST to be consistent with the other variable names and
avoid conflicts with anything else in the environment.
> jobs.groovy: use KCI_ prefix for all KernelCI environment variables

- Dockerfile
- docker-compose.yaml
Add a jenkins_docker_image build-time argument to the Dockerfile and
populate it from the JENKINS_DOCKER_IMAGE environment variable in
docker-compose.yaml to be able to choose which Jenkins Docker image to
use.  The default is still set to jenkins/jenkins:latest but for
production instances it's important to be able to set the exact
Jenkins revision to use.  For example, "jenkins/jenkins:2.232".
> Add jenkins_docker_image argument to choose Jenkins version

- config/default-auth.yaml
- config/jenkins.yaml
With the jenkins auth config in the main jenkins.yaml, it's impossible to override this to use a different authentication method.
Instead, move the auth into a seperate yaml file which can be overwritten/deleted by other deployments to use LDAP/github etc.
> Move jenkins auth settings to separate YAML

- plugins-extra.txt
To enable for all pipeline jobs using config-as-code, add this to
the 'unclassified' section of jenkins.yaml:
```
unclassified:
timestamperConfig:
allPipelines: true
elapsedTimeFormat: "'<b>'HH:mm:ss.S'</b> '"
systemTimeFormat: "'<b>'HH:mm:ss'</b> '"
```
Signed-off-by: Kevin Hilman <khilman@baylibre.com>
> plugins-extra: add timestamper

- jobs.groovy
- jobs/rootfs-builder.jpl
- jobs/rootfs-trigger.jpl
Move rootfs-builder.jpl and rootfs-trigger.jpl from
kernelci-core and update jobs.groovy file.
Signed-off-by: Lakshmipathi <lakshmipathi.ganapathi@collabora.com>
> Move rootfs jpl files from kernelci-core/jenkins

- jobs/build-trigger.jpl
Due to an intermittent issue with LAVA returning HTTP 502 when
querying the list of available devices, retry getting the lab info to
make it more resilient until the issue is fixed in LAVA.
> jobs/build-trigger.jpl: retry getting lab info

- plugins-extra.txt
The github-auth plugin is failing to install, and it's not actually
used.  Drop it from the plugins-extra.txt file.
> plugins-extra.txt: drop github-auth

- jobs.groovy
- jobs/build-trigger.jpl
- jobs/build.jpl
- jobs/rootfs-builder.jpl
Rather than having a hard-coded kernelci-backend API token ID, load it from the environement so each instance can have its own value.  Also use it in Kubernetes jobs to load the API token locally.
> Load KCI_API_TOKEN_ID from environment and use it on Kubernetes builders

- jobs/bisect.jpl
- jobs/build-trigger.jpl
- jobs/rootfs-builder.jpl
- jobs/test-runner.jpl
Use the new --db-token and --lab-token command line arguments which
replace the ambiguous --token argument.  This relies on the latest
kernelci-core version to be installed with the renamed arguments.
Depends on https://github.com/kernelci/kernelci-core/pull/457
> jobs/*.jpl: use --db-token and --lab-token

- jobs/build-trigger.jpl
Get the list of test jobs to run for each kernel build before starting
a test-runner job.  This is to avoid unnecessary overhead in Jenkins,
with many test-runner jobs started only to find out that no tests are
to be run.
> jobs/build-trigger.jpl: skip empty test-runner jobs

- jobs/bisect.jpl
Rename the KCI_TOKEN_ID parameter to KCI_API_TOKEN_ID as per the
change in jobs.groovy.
Fixes: ("d63355e1afad jobs.groovy: load KCI_API_TOKEN_ID from environment")
> T22773 jobs/bisect.jpl: fix KCI_API_TOKEN_ID parameter

- jobs/bisect.jpl
- jobs/build-trigger.jpl
- jobs/monitor.jpl
- jobs/rootfs-builder.jpl
- jobs/rootfs-trigger.jpl
- jobs/test-runner.jpl
Use new command-line arguments --build-config and --lab-config which
replace the generic --config one.
Depends on https://github.com/kernelci/kernelci-core/pull/465
> T23120 jobs/*.jpl: use new --{build,lab}-config arguments

- jobs/rootfs-trigger.jpl
Signed-off-by: Kevin Hilman <khilman@baylibre.com>
> jobs/rootfs-trigger: pass KCI_CORE_[URL|BRANCH]

- jobs/build-trigger.jpl
kselftest builds take a bit longer than other builds, tag them for
"medium" build nodes.
Signed-off-by: Kevin Hilman <khilman@baylibre.com>
> build-trigger: make kselftest configs medium

- restart-compose.sh
First run "docker-compose down" to try a clean shutdown of the Jenkins
container.  If for some reason the container is still there after
that, run "docker stop" command like before to ensure it's stopped.
> restart-compose.sh: first try a clean container shutdown

- jobs/build-trigger.jpl
- jobs/monitor.jpl
Fix issues with Jenkins exceptions, to retry when checking branches in the monitor job and to still send email reports when some error occurs in build-trigger.
> T23121 Handle Jenkins exceptions

- jobs/monitor.jpl
The trees_dir variable appears to be a leftover from previous
refactoring of the code, when the monitor job used to be updating git
mirrors.  This is now done in build-trigger.jpl.
Reported-by: Tim Orling <ticotimo@gmail.com>
> jobs/monitor.jpl: remove unused trees_dir variable

- jobs/bisect.jpl
There are some known issues with some LAVA labs when a timeout on the
server can cause an occasional HTTP 502 error.  To make the job more
resilient, retry up to 3 times when querying the lab info (i.e. the
list of device types).
This is similar to what is done in build-trigger.jpl, except that for
bisect.jpl the job needs to be aborted.
> jobs/bisect.jpl: retry "kci_test get_lab_info" up to 3 times

- scripts/buildroot-builder.sh
- scripts/push-source.py
Move the buildroot-builder.sh job from kernelci-core to
scripts/buildroot-builder.sh along with push-source.py since it's the
only job using this script.
> scripts: import buildroot-builder.sh from kernelci-core

- jobs.groovy
- scripts/kernel-arch-complete.sh
Import kernel-arch-complete.sh from kernelci-core and update
jobs.groovy to use it from this kernelci-jenkins repository rather
than kernelci-core.
> T25447 jobs.groovy: use local kernel-arch-complete.sh script

- jobs/bisect.jpl
The standalone Python scripts used for the bisection jobs are being
moved to a "scripts" directory in kernelci-core, so update bisect.jpl
to call them from that directory.
Depends on https://github.com/kernelci/kernelci-core/pull/581
> T25447 jobs/bisect.jpl: use scripts from kernelci-core scripts directory

- jobs/monitor.jpl
Run kci_build directly in the kernelci-core to rely on the default
local path to the build-configs.yaml file.  This is to avoid issues
when the file is being moved to the new config directory.
> T25969 jobs/monitor.jpl: use default build-configs.yaml path

- jobs/build.jpl
The k8s templates and scripts are being moved from templates/k8s to
config/k8s in kernelci-core.  Update build.jpl accordingly.
> jobs/build.jpl: update path to the k8s config in kernelci-core

- jobs/rootfs-builder.jpl
The rootfs config files are being moved to config/rootfs, so update
the --data-path value accordingly.
Ideally, this should be config/rootfs as the "debos" part can be
deduced from the YAML configuration, but it would require a few more
changes to clean this up.
> jobs/rootfs-builder.jpl: update --data-path to config/rootfs/debos

- jobs/build-trigger.jpl
- jobs/build.jpl
- jobs/test-runner.jpl
Save the new meta-data JSON files with bmeta, steps and artifacts.  Update the calls to kci_test with the command line changes related to the new meta-data.
> jobs/build.jpl: add steps.json and artifacts.json to artifacts

- jobs/build-trigger.jpl
Fix the regular expression when looking for kselftest jobs to schedule
them on medium builders.  The builds parameters now take the
"non-expanded" version of the defconfig, e.g. defconfig+kselftest
rather than the actual config fragment file name kernelci.config.
> jobs/build-trigger.jpl: fix kselftest config regex

- jobs.groovy
Add buildroot-staging job based on buildroot job. The job aim is to
build buildroot based rootfs images from the staging.kernelci.org
branch. This is useful when there are new features introduced to
buildroot and need to be tested before going to production.
Signed-off-by: Michal Galka <michal.galka@collabora.com>
> Add buildroot-staging job

- jobs/build-trigger.jpl
Check whether the current HEAD of the branch to build has already been
built before getting the lab-specific info.  Getting all the labs'
info can take a while and it's not necessary to do this before
checking the revision.  So this should speed things up when the queue
of trigger jobs gets congested.
> jobs/build-trigger.jpl: check new revision before lab info

- scripts/kernel-arch-complete.sh
Send the linux-next reports to the new LLVM Linux mailing list email
address llvm@lists.linux.dev.
Link: https://groups.io/g/kernelci/topic/moving_to/85147095
> kernel-arch-complete.sh: use new LLVM Linux mailing list

- jobs.groovy
Signed-off-by: lakshmipathi.g <lakshmipathi.ganapathi@collabora.com>
> jobs.groovy: Add ROOTFS_TYPE param for rootfs trigger and builder jobs

- jobs/build.jpl
The Docker image for Kubernetes builds is being renamed from build-k8s
to k8s, so update the Jenkins job accordingly.
> jobs/build.jpl: use kernelci/k8s Docker image

- jobs.groovy
- jobs/rootfs-builder.jpl
- jobs/rootfs-trigger.jpl
Add buildroot support to rootfs-builder and rootfs-trigger jobs.
Depends on #63
> rootfs: Create a baseline buildroot rootfs image

- jobs/build-trigger.jpl
Stop generating kernel config fragments in the source tarball as this
can now be done in each kernel build.  It means the tarball is now
purely the kernel source code with no changes, and build
configurations don't need to list the fragments at the top level any
more.
> jobs/build-trigger.jpl: don't generate fragments in tarball

- jobs/build-trigger.jpl
The fragment files need to be present in order for a build config to
be scheduled with it.  Generate the fragment files again but in the
step that lists the build configs rather than when uploading the
source tarball like it was done previously.
Fixes: e243cee9e129 ("jobs/build-trigger.jpl: don't generate fragments in tarball")
> jobs/build-trigger.jpl: generate the fragments to list all configs

- jobs.groovy
Use the 'main' branch from kernelci-core for rootfs builds as they are
typically run before the kernelci.org branch gets updated.  This is to
allow testing the new rootfs images on staging ahead of the actual
production release.
> jobs.groovy: use the 'main' branch for rootfs builds

- jobs/rootfs-builder.jpl
Use the rootfs type to determine the Docker image name rather than
if-else logic.
> jobs/rootfs-builder.jpl: remove if-else for Docker image

- jobs/rootfs-trigger.jpl
Use the rootfs type provided by 'kci_rootfs list_variants' directly
and pass that to the rootfs builder jobs to avoid any config-specific
logic in the code.
Depends on https://github.com/kernelci/kernelci-core/pull/1035
> jobs/rootfs-trigger.jpl: use rootfs type from kci_rootfs

- jobs/rootfs-builder.jpl
After changes in https://github.com/kernelci/kernelci-core/pull/1050 it is
possible to simplify build configuration, as all custom commands moved into
kci_rootfs.
> kci_rootfs: --output option, unified build config

- Dockerfile
- plugins-base.txt
Use the newer `jenkins-plugin-cli` command to install plugins and add `ssh-agent` to the list of plugins to install.  This will be useful when uploading files using scp in particular.
> Add ssh-agent plugin

- jobs/rootfs-builder.jpl
Diagnostic commands can work only for kernelci/chromiumos docker image
> CHROMEOS Fix building debos, as it required for flashing image

- jobs/rootfs-builder.jpl
Chromebook builds are estimated to take even more time than vm image,
approximately it took 10 hours on average Core i7.
> CHROMEOS Increase build timeout for rootfs

- jobs.groovy
- jobs/build-trigger.jpl
- jobs/monitor.jpl
Rework how the last commit is being handled by updating it in the
monitor job rather than the build-trigger job.  This avoids scheduling
potentially many duplicate build-trigger jobs when the queue is
already full.  Instead, pass the git commit sha1 to the build-trigger
job and only build if it the current branch matches that.
> jobs/{monitor,build-trigger}.jpl: update last commit in monitor

- jobs.groovy
- jobs/rootfs-trigger.jpl
Add a PIPELINE_VERSION parameter to the rootfs-trigger job to be able
to supply one explicitly.  If the parameter is empty, a pipeline name
will be created automatically like before.
> jobs/rootfs-trigger.jpl: add PIPELINE_VERSION parameter

- jobs/bisect.jpl
- jobs/build-trigger.jpl
- jobs/build.jpl
- jobs/monitor.jpl
- jobs/rootfs-builder.jpl
- jobs/rootfs-trigger.jpl
- jobs/test-runner.jpl
Update the copyright headers for all the Jenkins job files with
authors and years.
> jobs/*.jpl: update all copyright headers

- jobs/rootfs-builder.jpl
Set rootfs image upload path to
rootfs/${rootfs_type}/${config}/${pipeline_version} previous setting
made it hard to browse through the artifacts from different builds as it
the builds were grouped by pipeline version before config names.
Signed-off-by: Michal Galka <michal.galka@collabora.com>
> CHROMEOS jobs/rootfs-builder.jpl: Fix rootfs image upload path

- jobs/rootfs-builder.jpl
Use the kernelci/cros-sdk image to build Chromium OS user-space
images.  This Docker image can also be used to build other things from
the Chromium OS source tree such as Depthcharge firmware and kernels,
which is why it doesn't match the rootfs type name.
Depends on https://github.com/kernelci/kernelci-core/pull/1203
> CHROMEOS jobs/rootfs-builder.jpl: use cros-sdk image to build Chromium OS

- jobs/rootfs-builder.jpl
The Chrome OS images take a very long time to complete, potentially
over 24h on regular builders.  Drop the timeout as it's too easy to
reach it and since jobs are started by hand it's not an issue if they
need to be also canceled by hand.
> CHROMEOS jobs/rootfs-builder.jpl: drop build timeout

- jobs/rootfs-builder.jpl
Fix indentation in rootfs-builer.jpl.
Fixes: 99cafb3e46f3 ("CHROMEOS jobs/rootfs-builder.jpl: Fix rootfs image upload path")
> CHROMEOS jobs/rootfs-builder.jpl: fix indentation

- jobs/rootfs-append-cros-image.jpl
Add Jenkins job which appends Chrome OS image to cros-flash rootfs image
and uploads the full image to storage.
Signed-off-by: Michal Galka <michal.galka@collabora.com>
> CHROMEOS jobs/rootfs-append-cros-image.jpl: Add rootfs-append-cros-image job

- jobs/build.jpl
- src/org/kernelci/util/Job.groovy
Update the Docker image names to use the ones produced by `kci_docker`, both with the Kubernetes tools used in Jenkins and the compiler toolchains running in Kubernetes.
> Use kci_docker images for kernel builds

- jobs/rootfs-builder.jpl
Use the new Docker images with the kernelci fragment added.
> rootfs-builder.jpl: use new Docker images with :kernelci

- jobs/build-trigger.jpl
As reported in kernelci maillist, gki_defconfig fails to build,
during testing we discovered that during linking, because of LTO
build process might consume more than 18Gbyte of RAM, which
exceed capacity of normal builders (4Gbyte).
This patch set gki_defconfig to build on k8s-big nodes,
that have 32Gbyte of RAM.
> build-trigger.jpl: build gki_defconfig on k8s-big nodes

- jobs/bisect.jpl
- jobs/build-trigger.jpl
- jobs/monitor.jpl
- jobs/rootfs-trigger.jpl
- jobs/test-runner.jpl
Use the new kernelci image (or kernelci/staging-kernelci on staging using DOCKER_BASE) instead of build-base which is now deprecated.
> jobs/*.jpl: use kernelci Docker image rather than build-base

- jobs/bisect.jpl
- jobs/build-trigger.jpl
- jobs/build.jpl
- jobs/monitor.jpl
- jobs/test-runner.jpl
- src/org/kernelci/util/Job.groovy
Rather than doing git clones, use the `kernelci` Python package already installed in the Docker image.
> Use kernelci package from Docker image

- jobs.groovy
- jobs/rootfs-trigger.jpl
Add ROOTFS_TYPE parameter to support triggering builds for a specific rootfs type.
Signed-off-by: Michal Galka <michal.galka@collabora.com>
> rootfs-trigger.jpl: Add ROOTFS_TYPE parameter

- jobs/bisect.jpl
Stop cloning kernelci-core as it's already present in the new Docker images.  Update all instances where this was used to simplify the code.
> jobs/bisect.jpl: drop kernelci-core git clone

- jobs.groovy
- jobs/rootfs-trigger.jpl
rootfs_trigger.jpl:
Add parsing of space separated lists of rootfs architecture names and rootfs types.
jobs.groovy: rootfs-build-trigger description adjustments
Adjust parameters description to match with the current implementation accepting lists of rootfs types and architectures.
Depends on: https://github.com/kernelci/kernelci-core/pull/1445
> T37847 multiple rootfs and archs

- jobs/build.jpl
Several steps to improve job run reliability:
1)kubectl get nodes are not critical for process and should not cause job termination, ignore exit code. This happen often.
2)Make .kube configuration file mount as read only, as this volume is shared by multiple processed and getting corrupted. 
3)Do not run "rm -rf *" as we are supposed to run in new docker image.
> build.jpl: Improve reliability of build process

- jobs/build.jpl
Kubernetes config directory might contain temporary files, that might not be copied or disappear during copy. It is more safe to copy only necessary file, otherwise error might appear:
```
+ cp -r /.kube-host/cache /.kube-host/config /.kube-host/http-cache /tmp/.kube
cp: cannot stat '/.kube-host/cache/http/ec5ba2e85e057052ea061fcd28378a2094b832d5f9168e43cb599b8f5fbfb0b7': No such file or directory
```
> build.jpl: Copy only necessary config file

- jobs/bisect.jpl
- jobs/build-trigger.jpl
- jobs/build.jpl
- jobs/monitor.jpl
- jobs/rootfs-builder.jpl
- jobs/rootfs-trigger.jpl
- jobs/test-runner.jpl
As explained in https://issues.jenkins.io/browse/JENKINS-45888, to solve problems with zombies we need to add --init flag for docker image.
Fixes https://github.com/kernelci/kernelci-core/issues/1499
> *.jpl: Add --init flag for image.inside()

- jobs/monitor.jpl
Print the commit number used when triggering a new build.  This helps keeping track of what the job is doing and diagnose issues when it fails.
> jobs/monitor.jpl: print commit number when triggering build

- jobs/build.jpl
As gcp got deprecated it causes builds to fail in jenkins. This is desperate attempt to find quick workaround for this issue.
> build.jpl: Temporary workaround to fix gcp auth plugin deprecation

- jobs.groovy
- jobs/bisect.jpl
Use the new kci_build --storage-config / --storage-cred arguments with the KCI_STORAGE_CONFIG job parameter.
> bisect.jpl: use kci_build --storage-config

- jobs/bisect.jpl
- jobs/build-trigger.jpl
- jobs/test-runner.jpl
Update all the jobs to use the new --runtime-* command line arguments.
Depends on https://github.com/kernelci/kernelci-core/pull/1737
> jobs/*: replace --lab-* arguments with --runtime-*

- jobs/rootfs-builder.jpl
We are generating docker image with :kernelci fragment, also kernelci-core doesn't work standalone anymore, as it need some dependencies.
> CHROMEOS rootfs-builder.jpl: Add missing kernelci fragment

- jobs/rootfs-builder.jpl
Fixes https://github.com/kernelci/kernelci-core/issues/1992
Tested at https://bot.staging.kernelci.org/job/rootfs-builder/564/console
Fix suggested at: https://github.com/go-debos/debos/issues/309
> rootfs-builder.jpl: Fix build issues on latest version of Ubuntu runner

- jobs.groovy
Bisections are currently disabled due to resource constraints.  We expect this to be temporary.
> temporarily disabling bisections

- scripts/kernel-arch-complete.sh
The MediaTek tree changed from "matthiasbgg" to "mediatek": reflect the changes here to keep sending out results via email. While at it, also add Angelo's email address.
> scripts/kernel-arch-complete: Fix MediaTek tree and add Angelo's mail

- jobs/test-runner.jpl
On legacy this is just slowing down things.
Only thing we need for a while is android builds.
> feat(test-runner.jpl): Try to skip lab tests

- jobs.groovy
As planned, sunsetting legacy functions one by one, now its turn of bisections.
> jobs.groovy: Disable bisection
